### ISSUE TITLE
Client method use on the server

### ISSUE THREAD

**Issue by KyuubiYoru** [Ladysnake/Spawn-Lanterns#2]
I tried to run this mod witch the AOF 3 (2.4.1) modpack, the Client started without issues but the Server crashed on startup.
Is this a problem with the MC version 1.16.3 or a conflict with an different mod?

`[Server thread/FATAL]: Mixin apply failed spawnlanterns.mixins.json:InfoMixin -> net.minecraft.class_1948$class_5262: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method method_27823 in spawnlanterns.mixins.json:InfoMixin was not located in the target class net.minecraft.class_1948$class_5262. Using refmap spawnlanterns-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method method_27823 in spawnlanterns.mixins.json:InfoMixin was not located in the target class net.minecraft.class_1948$class_5262. Using refmap spawnlanterns-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:423) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:399) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:327) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:286) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.class_1948.method_27815(class_1948.java:169) ~[intermediary-server.jar:?]
	at net.minecraft.class_3215.method_14161(class_3215.java:361) ~[intermediary-server.jar:?]
	at net.minecraft.class_3215.method_12127(class_3215.java:337) ~[intermediary-server.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:348) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:868) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:303) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:808) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:667) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:254) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]`

**Comment by doctor4t** [comment]
My fault, I used a client method so that's why it crashes. Will fix in next version.

**Comment by AuracleTech** [comment]
Same issue here :'( we were so happy to test it
